version: '3.9'

services:
  nextcloud:
      image: nextcloud:stable
      container_name: "nextcloud"
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./nextcloud:/var/www/html:rw
      env_file:
        - .env
      depends_on:
        - db
      networks:
        - default
  db:
    image: postgres
    restart: always
    container_name: "nextcloud-database"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - default
