version: '3.9'

networks:
  traefic:
    external: true
    name: traefic
  nextcloud:
    name: nextcloud

services:
  nextcloud:
      image: nextcloud:24.0-fpm
      container_name: "nextcloud"
      restart: unless-stopped
      volumes:
        - ./nextcloud:/var/www/html:rw
      env_file:
        - .env
      depends_on:
        - db
      networks:
        - traefic
        - nextcloud
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`${HOST}`)"
        - "traefik.http.routers.whoami.entrypoints=web,websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=production"
  db:
    image: postgres
    restart: always
    container_name: "nextcloud-database"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - nextcloud
