version: '3.9'

services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
    - 8303:80
    - 444:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./configs/nginx/certbot:/etc/nginx/certbot:ro
      - ./configs/certbot/conf:/etc/letsencrypt:rw
      - ./configs/certbot/www:/var/www/certbot:rw
      - ./nextcloud:/var/www/html:ro
      - ./logs/nginx:/var/log/nginx
      # - ./nginx/certs:/etc/ssl/certs
      # - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./nginx/certbot:/etc/nginx/certbot:ro
      # - ./certbot/conf:/etc/letsencrypt:rw
      # - ./certbot/www:/var/www/certbot:rw
      # - ./nextcloud:/var/www/html:ro
      # - ./logs/nginx:/var/log/nginx
  # certbot:
  #   restart: unless-stopped
  #   image: certbot/certbot:latest
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./certbot/conf:/etc/letsencrypt:rw
  #     - ./certbot/www:/var/www/certbot:rw
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./databases/data:/var/lib/postgresql/data
    env_file:
      - .env.db
  nextcloud:
    image: nextcloud:fpm
    restart: unless-stopped
    # ports:
    #   - "127.0.0.1:9000:9000"
    volumes:
      - ./nextcloud:/var/www/html:rw
    env_file:
      - .env
    depends_on:
      - db
  