version: '3.9'

networks:
  proxy:
    external: true

services:
  nextcloud:
      image: nextcloud:stable
      container_name: "nextcloud"
      restart: unless-stopped
      volumes:
        - ./nextcloud:/var/www/html:rw
      env_file:
        - .env
      depends_on:
        - db
      networks:
        - proxy
        - default
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.nextcloud-secure.entrypoints=web,websecure"
        - "traefik.http.routers.nextcloud-secure.rule=Host(`${HOST}`)"
        - "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
        - "traefik.http.routers.nextcloud-secure.tls=true"
        - "traefik.http.routers.nextcloud-secure.tls.certresolver=production"
        - "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
  db:
    image: postgres
    restart: always
    container_name: "nextcloud-database"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - default
